repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.3
  hooks:
    - id: commitizen
      additional_dependencies: [cz-conventional-gitmoji]

- repo: https://github.com/ljnsn/cz-conventional-gitmoji
  rev: v0.7.0
  hooks:
    - id: conventional-gitmoji
