;;; octicons-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from octicons.el

(autoload 'octicons "octicons" "\
Return octicons code point

(fn FONT-NAME)" t)
(register-definition-prefixes "octicons" '("octicons--"))


;;; Generated autoloads from octicons-data.el

(register-definition-prefixes "octicons-data" '("octicons-alist"))

;;; End of scraped data

(provide 'octicons-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; octicons-autoloads.el ends here
